package com.notary.framework.thridpart.webservice.cxf.sjjk;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.1.13
 * 2017-10-10T16:53:39.058+08:00
 * Generated source version: 3.1.13
 * 
 */

//正式地址：http://205.2.3.2:88/yjwgx/services/zwwwSjjk
@WebService(targetNamespace = "http://205.2.3.2:88/yjwgx/services/zwwwSjjk", name = "SjjkServiceImpl")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SjjkServiceImpl {

    //@WebResult(name = "dataSynchronousResponesReturn", targetNamespace = "http://205.0.3.99:88/yjwgx/services/zwwwSjjk", partName = "dataSynchronousResponesReturn")
	@WebResult(name = "dataSynchronousResponesReturn",
            targetNamespace = "http://sjjk.manage.rjcourt", partName = "dataSynchronousResponesReturn")
	
	@WebMethod
    public String dataSynchronousRespones(
            @WebParam(partName = "xml", name = "xml")
            String xml
    );
}
